# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

include:
  - project: 'dhei/teams/io/templates/gitlab-pipelines'
    file: '/helm/PublishChart.gitlab-ci.yml'
    ref: develop
  - project: "dhei/teams/hyperion/dev/src/foundation-build"
    file: "/pipelines/opensource-pipeline.yaml"
    ref: main
    rules:
      - if: $CI_PROJECT_NAME == "stargate-kong-charts"

.setup_job_basics: &setup_job_basics
  tags:
  - otc_run_sysbox_m

variables:
  GITHUB_PROJECT_PATH: "telekom/stargate-kong-charts"
  GITLAB_PROJECT_PATH: "dhei/teams/io/products/stargate/stargate-chart"
  GITLAB_SOURCE_BRANCH: main
