include:
- project: 'tif/gitlab-pipelines'
  file: '/helm/PublishChart.gitlab-ci.yml'
  ref: master

variables:
  DOCKER_AUTH_CONFIG: $DOCKER_AUTH_CONFIG_TIF

stages:
- bundle
- test
- publish

default:
  tags:
  - run_docker

.get-plugin: &get-plugin
  image: mtr.external.otc.telekomcloud.com/tif/luarocks
  script:
  - |
    mkdir -p $CI_PROJECT_DIR/plugins && cd $CI_PROJECT_DIR/plugins
    git config --global url.https://github.com/.insteadOf git://github.com/ && \
    luarocks install --local kong-plugin-${PLUGIN_NAME} && \
    luarocks pack --local kong-plugin-${PLUGIN_NAME} && \
    ls -l $CI_PROJECT_DIR/plugins

bundle:jwt-keycloak:
  stage: bundle
  variables:
    PLUGIN_NAME: jwt-keycloak
  extends: .get-plugin
  artifacts:
    paths:
    - $CI_PROJECT_DIR/plugins

publish:chart:
  dependencies:
  - bundle:jwt-keycloak
