include:
  - project: 'dhei/teams/io/templates/gitlab-pipelines'
    file: '/helm/PublishChart.gitlab-ci.yml'
    ref: artifactory_test

.setup_job_basics: &setup_job_basics
  tags:
  - otc_run_docker_m