apiVersion: v2
name: stargate
version: 5.2.2
appVersion: 2.0.0
description: Kong API gateway provided by DHEI
dependencies:
- name: postgresql
  version: 1.0.0
maintainers:
- name: Mike Herwig
  email: Mike.Herwig@external.t-systems.com
- name: Christian Stein
  email: steinc@external.telekom.de
- name: Christian Knott
  email: christian.knott@external.telekom.de
