global:
  platform: "kubernetes"
  project_prefix: "tif-"
  storageclass: "cns"
  externalDnsTarget: changeme
  domain:
    internal:
      url: "changeme-internal.tif.telekom.de"

enterprise:
  license: changeme

manager:
  enabled: true
  session:
    secret: changeme

portal:
  enabled: false
  session:
    secret: changeme

rbac:
  enabled: true
  kongAdminPassword: changeme

# You can add custom plugins here:
# Note:
# The plugins must be deployed as configmaps and correctly referenced here
# You can either deploy the configmaps seperaty in a previous process
# or you place the configmaps into the templates directory of this Helm chart
# If you provide a sha256 sum you will tigger a re-deployment of Kong when the
# plugin and its sha256 sum changes later!
# customPlugins:
#   - name: custom1
#     configMap: kong-plugin-custom1-5e67ca89
#     sha256sum: f4950244a2cc624125a2cde3febd33dfadf7d4f8d66fb59f3e076b5fadd87068
#   - name: custom2
#     configMap: kong-plugin-custom2-6a2bc71b
#     sha256sum: bfc0367fce13159ac68ff19be9c5fc081c5c2fa55eedf24a281e0d9d190a4b46

externalDatabase:
  enabled: false
# host: some-external-postgresql-database.example.com
# port: '5432'

# Warning: 
# If you disable rbac exposing the Admin API can be dangerous
exposeAdminApi: true

# values used by nginx directives
sslVerify: false
sslVerifyDepth: '1'
disableUpstreamCache: false

replicas: 1

resources:
  requests:
    cpu: 750m
    memory: 1024Mi

postgres:
  pvc:
    keepOnDelete: false
  
# data_locations: '/var/lib/postgresql/data'
  # use this data location for postgresql-95-rhel7 based postgres images
  data_locations: '/var/lib/pgsql/data'

# port: 5432

  database: kong  
  user: kong
  password: changeme

  replicas: 1

  resources:
    limits:
      memory: "512Mi"
