global:
  platform: kubernetes
  project_prefix: "tif-"
  storageclass: "gp2"
  externalDnsTarget: changeme
  domain: ""

  # If imagePullSecrets is not empty, a pull secret will be deployed for each entry otherwise no pull secret will be deployed
  # If you use tif-infra-pipeline (TIF installer) this will be set automatically
  # imagePullSecrets:
  #   - name: mtr-tif-public
  #     registry: https://mtr.external.otc.telekomcloud.com
  #     username: changeme
  #     password: changeme
  imagePullSecrets: []

# You can list files (in /templates) here that should cause a re-deployment of your application
# when their contents change
# This makes sense if you change configMaps or secrets and you
# want your deployment to use the latest configuration
#
# templateChangeTriggers:
#   - my-custom-configmap.yaml
#   - my-custom-kong-plugin.yaml
templateChangeTriggers: []

# You can force using a specific image here:
# image: 'mtr.external.otc.telekomcloud.com/tif-public/tif-kong-ee:1.0.0'

enterprise:
  license: changeme

# Warning: 
# If you disable RBAC exposing the Admin API can be dangerous
# Note that RBAC will only work when Kong in running in enterprise edition (enterprise.license is provided) 
rbac:
  enabled: true
  kongAdminPassword: changeme



zipkin:
  enabled: false
  collectorUrl: ""
  # sampleRatio: 0.001
  # defaultServiceName: "kong-apigateway"
  # includeCredential: "true"
  # Set job retries and maximum runtime (default values preset)
  # setupJob:
  #   backoffLimit: 20
  #   activeDeadlineSeconds: 300


# You can add custom plugins here:
# Note:
# The plugins must be deployed as configmaps and correctly referenced here
# You can either deploy the configmaps seperaty in a previous process
# or you place the configmaps into the templates directory of this Helm chart
#
# Note: If your configMap name will not change with future updates of your Kong plugin (e.g.: no checksum in name)
# you can list the configMap yaml file in the templateChangeTriggers list above
# to tigger a re-deployment of Kong
#
# customPlugins:
#   - name: custom1
#     configMap: kong-plugin-custom1-5e67ca89
#   - name: custom2
#     configMap: kong-plugin-custom2-6a2bc71b
customPlugins: []

externalDatabase:
  enabled: false
# host: some-external-postgresql-database.example.com
# port: '5432'

# Enable Admin API and whether it is http or https
# Warning: 
# Enabled Admin API with disabled RBAC can be dangerous
adminApi:
  enabled: true
  tls:
    enabled: false
# Activate Admin API ingress and set a dedicated hostname
  ingress:
    enabled: true
    # hostname: ""
    annotations: {}

# Configure Kong Manager
manager:
  enabled: true
  tls:
    enabled: false
  session:
    secret: changeme
  ingress:
    enabled: true
    # hostname: ""
    annotations: {}

# Configure the Portal
portal:
  enabled: false
  tls:
    enabled: false
  session:
    secret: changeme
  ingress:
    enabled: true
    # hostname: ""
    annotations: {}

# Activate proxy ingress and set a dedicated hostname
proxy:
  ingress:
    enabled: true
    # hostname: ""
    annotations: {}

# values used by nginx directives
sslVerify: false
sslVerifyDepth: '1'

# You can define the truststore for SSL verification by setting your CAs in PEM format here 
#
# trustedCaCertificates: |
#   -----BEGIN CERTIFICATE-----
#   <CA certificate 01 in PEM format here>
#   -----END CERTIFICATE-----
#   -----BEGIN CERTIFICATE-----
#   <CA certificate 02 in PEM format here>
#   -----END CERTIFICATE-----
#   -----BEGIN CERTIFICATE-----
#   <CA certificate 03 in PEM format here>
#   -----END CERTIFICATE-----

# You can define the default HTTPS server certificate by specifing the secret with private-key/certificate here
# Note: additional route-specific server certificates can by configured and assigned to SNIs at runtime. This is only a default certificate
#
# defaultTlsSecret: "mysecret"

disableUpstreamCache: false

replicas: 1

zipkin:
  enabled: false
  collectorUrl: ""
  # sampleRatio: 0.001
  # includeCredential: "true"
  # defaultServiceName: "kong-apigateway"
  # Set job retries and maximum runtime (default values preset)
  # setupJob:
  #   backoffLimit: 20
  #   activeDeadlineSeconds: 300

prometheus:
  enabled: true 
# port: 9542
# path: /metrics
# setupJob:
#   backoffLimit: 20
#   activeDeadlineSeconds: 300

resources:
  requests:
    cpu: 750m
    memory: 1024Mi

postgres:
  pvc:
    keepOnDelete: false
  
# data_locations: '/var/lib/postgresql/data'
  # use this data location for postgresql-95-rhel7 based postgres images
  data_locations: '/var/lib/pgsql/data'

# port: 5432

  database: kong  
  user: kong
  password: changeme

  replicas: 1

  resources:
    limits:
      memory: "512Mi"
