global:
  project_prefix: "tif-"
  storageclass: "cns"
  domain:
    internal:
      url: "changeme-internal.tif.telekom.de"

image:
  repository: kong
  tag: '2.0'

# Warning: Might be unsecure to expose the adminapi
enableAdmin: false

resources:
  requests:
    cpu: 750m
    memory: 1024Mi

postgres:
  image:
    repository: postgres
    tag: '9.5'

  database: kong  
  user: kong
  password: changeme

  replicas: 1
  resources:
    limits:
      memory: "512Mi"
