{{- if .Values.keyRotation.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "kong.labels" $ | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "kong.labels" $ | nindent 4 }}
spec:
  secretName: {{ .Release.Name }}-tls-rotator
  secretTemplate:
    annotations:
      rotator.gw.ei.telekom.de/destination-secret-name: {{ .Release.Name }}-tls-rotated
      rotator.gw.ei.telekom.de/source-secret: "true"
  issuerRef:
    name: {{ .Release.Name }}
    kind: Issuer

  {{- if not .Values.keyRotation.additionalSpecValues }}
  privateKey:
    rotationPolicy: Never
    algorithm: RSA
    encoding: PKCS8
    size: 2048

  duration: 2160h
  renewBefore: 1080h

  commonName: Stargate
  {{- else }}
  {{ .Values.keyRotation.additionalSpecValues | toYaml | nindent 2 }}
  {{- end }}

{{- end }}