
{{- if not .Values.trustedCaCertificates.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dhei-defaults
  labels: {{- include "kong.labels" $ | nindent 4 }}
data:
  trusted-ca-certificates.pem: |
    # cat ./ca_certificates_in_pem_format/* > ca_certificates.crt
    # openssl crl2pkcs7 -nocrl -certfile ca_certificates.crt | openssl pkcs7 -print_certs -text > bundle.crt
    # Output of bundle.crt:
    Certificate:
        Data:
            Version: 3 (0x2)
            Serial Number: 1 (0x1)
            Signature Algorithm: sha256WithRSAEncryption
            Issuer: C=DE, O=T-Systems Enterprise Services GmbH, OU=T-Systems Trust Center, CN=T-TeleSec GlobalRoot Class 2
            Validity
                Not Before: Oct  1 10:40:14 2008 GMT
                Not After : Oct  1 23:59:59 2033 GMT
            Subject: C=DE, O=T-Systems Enterprise Services GmbH, OU=T-Systems Trust Center, CN=T-TeleSec GlobalRoot Class 2
            Subject Public Key Info:
                Public Key Algorithm: rsaEncryption
                    RSA Public-Key: (2048 bit)
                    Modulus:
                        00:aa:5f:da:1b:5f:e8:73:91:e5:da:5c:f4:a2:e6:
                        47:e5:f3:68:55:60:05:1d:02:a4:b3:9b:59:f3:1e:
                        8a:af:34:ad:fc:0d:c2:d9:48:19:ee:69:8f:c9:20:
                        fc:21:aa:07:19:ed:b0:5c:ac:65:c7:5f:ed:02:7c:
                        7b:7c:2d:1b:d6:ba:b9:80:c2:18:82:16:84:fa:66:
                        b0:08:c6:54:23:81:e4:cd:b9:49:3f:f6:4f:6e:37:
                        48:28:38:0f:c5:be:e7:68:70:fd:39:97:4d:d2:c7:
                        98:91:50:aa:c4:44:b3:23:7d:39:47:e9:52:62:d6:
                        12:93:5e:b7:31:96:42:05:fb:76:a7:1e:a3:f5:c2:
                        fc:e9:7a:c5:6c:a9:71:4f:ea:cb:78:bc:60:af:c7:
                        de:f4:d9:cb:be:7e:33:a5:6e:94:83:f0:34:fa:21:
                        ab:ea:8e:72:a0:3f:a4:de:30:5b:ef:86:4d:6a:95:
                        5b:43:44:a8:10:15:1c:e5:01:57:c5:98:f1:e6:06:
                        28:91:aa:20:c5:b7:53:26:51:43:b2:0b:11:95:58:
                        e1:c0:0f:76:d9:c0:8d:7c:81:f3:72:70:9e:6f:fe:
                        1a:8e:d9:5f:35:c6:b2:6f:34:7c:be:48:4f:e2:5a:
                        39:d7:d8:9d:78:9e:9f:86:3e:03:5e:19:8b:44:a2:
                        d5:c7
                    Exponent: 65537 (0x10001)
            X509v3 extensions:
                X509v3 Basic Constraints: critical
                    CA:TRUE
                X509v3 Key Usage: critical
                    Certificate Sign, CRL Sign
                X509v3 Subject Key Identifier: 
                    BF:59:20:36:00:79:A0:A0:22:6B:8C:D5:F2:61:D2:B8:2C:CB:82:4A
        Signature Algorithm: sha256WithRSAEncryption
            31:03:a2:61:0b:1f:74:e8:72:36:c6:6d:f9:4d:9e:fa:22:a8:
            e1:81:56:cf:cd:bb:9f:ea:ab:91:19:38:af:aa:7c:15:4d:f3:
            b6:a3:8d:a5:f4:8e:f6:44:a9:a7:e8:21:95:ad:3e:00:62:16:
            88:f0:02:ba:fc:61:23:e6:33:9b:30:7a:6b:36:62:7b:ad:04:
            23:84:58:65:e2:db:2b:8a:e7:25:53:37:62:53:5f:bc:da:01:
            62:29:a2:a6:27:71:e6:3a:22:7e:c1:6f:1d:95:70:20:4a:07:
            34:df:ea:ff:15:80:e5:ba:d7:7a:d8:5b:75:7c:05:7a:29:47:
            7e:40:a8:31:13:77:cd:40:3b:b4:51:47:7a:2e:11:e3:47:11:
            de:9d:66:d0:8b:d5:54:66:fa:83:55:ea:7c:c2:29:89:1b:e9:
            6f:b3:ce:e2:05:84:c9:2f:3e:78:85:62:6e:c9:5f:c1:78:63:
            74:58:c0:48:18:0c:99:39:eb:a4:cc:1a:b5:79:5a:8d:15:9c:
            d8:14:0d:f6:7a:07:57:c7:22:83:05:2d:3c:9b:25:26:3d:18:
            b3:a9:43:7c:c8:c8:ab:64:8f:0e:a3:bf:9c:1b:9d:30:db:da:
            d0:19:2e:aa:3c:f1:fb:33:80:76:e4:cd:ad:19:4f:05:27:8e:
            13:a1:6e:c2
    -----BEGIN CERTIFICATE-----
    MIIDwzCCAqugAwIBAgIBATANBgkqhkiG9w0BAQsFADCBgjELMAkGA1UEBhMCREUx
    KzApBgNVBAoMIlQtU3lzdGVtcyBFbnRlcnByaXNlIFNlcnZpY2VzIEdtYkgxHzAd
    BgNVBAsMFlQtU3lzdGVtcyBUcnVzdCBDZW50ZXIxJTAjBgNVBAMMHFQtVGVsZVNl
    YyBHbG9iYWxSb290IENsYXNzIDIwHhcNMDgxMDAxMTA0MDE0WhcNMzMxMDAxMjM1
    OTU5WjCBgjELMAkGA1UEBhMCREUxKzApBgNVBAoMIlQtU3lzdGVtcyBFbnRlcnBy
    aXNlIFNlcnZpY2VzIEdtYkgxHzAdBgNVBAsMFlQtU3lzdGVtcyBUcnVzdCBDZW50
    ZXIxJTAjBgNVBAMMHFQtVGVsZVNlYyBHbG9iYWxSb290IENsYXNzIDIwggEiMA0G
    CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCqX9obX+hzkeXaXPSi5kfl82hVYAUd
    AqSzm1nzHoqvNK38DcLZSBnuaY/JIPwhqgcZ7bBcrGXHX+0CfHt8LRvWurmAwhiC
    FoT6ZrAIxlQjgeTNuUk/9k9uN0goOA/FvudocP05l03Sx5iRUKrERLMjfTlH6VJi
    1hKTXrcxlkIF+3anHqP1wvzpesVsqXFP6st4vGCvx9702cu+fjOlbpSD8DT6Iavq
    jnKgP6TeMFvvhk1qlVtDRKgQFRzlAVfFmPHmBiiRqiDFt1MmUUOyCxGVWOHAD3bZ
    wI18gfNycJ5v/hqO2V81xrJvNHy+SE/iWjnX2J14np+GPgNeGYtEotXHAgMBAAGj
    QjBAMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBS/
    WSA2AHmgoCJrjNXyYdK4LMuCSjANBgkqhkiG9w0BAQsFAAOCAQEAMQOiYQsfdOhy
    NsZt+U2e+iKo4YFWz827n+qrkRk4r6p8FU3ztqONpfSO9kSpp+ghla0+AGIWiPAC
    uvxhI+YzmzB6azZie60EI4RYZeLbK4rnJVM3YlNfvNoBYimipidx5joifsFvHZVw
    IEoHNN/q/xWA5brXethbdXwFeilHfkCoMRN3zUA7tFFHei4R40cR3p1m0IvVVGb6
    g1XqfMIpiRvpb7PO4gWEyS8+eIVibslfwXhjdFjASBgMmTnrpMwatXlajRWc2BQN
    9noHV8cigwUtPJslJj0Ys6lDfMjIq2SPDqO/nBudMNva0Bkuqjzx+zOAduTNrRlP
    BSeOE6Fuwg==
    -----END CERTIFICATE-----

    Certificate:
        Data:
            Version: 3 (0x2)
            Serial Number: 1 (0x1)
            Signature Algorithm: sha1WithRSAEncryption
            Issuer: C=DE, O=Deutsche Telekom AG, OU=Trust Center, CN=Deutsche Telekom Internal Root CA 1
            Validity
                Not Before: Nov 15 12:28:30 2007 GMT
                Not After : Nov 15 23:59:59 2027 GMT
            Subject: C=DE, O=Deutsche Telekom AG, OU=Trust Center, CN=Deutsche Telekom Internal Root CA 1
            Subject Public Key Info:
                Public Key Algorithm: rsaEncryption
                    RSA Public-Key: (2048 bit)
                    Modulus:
                        00:ab:55:95:04:79:bf:96:55:94:02:7d:9c:ef:b0:
                        fa:28:54:82:ef:16:6c:e1:3b:d8:cf:78:82:49:a0:
                        d9:40:f5:57:7f:05:dc:b7:f7:c1:0e:82:ce:c5:7c:
                        96:9b:92:6c:fa:30:8a:26:6e:bd:be:9a:b6:02:c8:
                        55:9a:fd:f6:37:02:29:1f:2d:ec:19:4c:1d:3c:f3:
                        35:29:f3:c4:55:fe:5c:21:b7:22:08:73:65:9e:c3:
                        de:68:46:c0:8b:40:69:15:52:d1:18:70:a6:e2:ec:
                        08:3d:ab:1e:08:3f:49:d4:2f:be:a7:c5:b4:3a:be:
                        83:c8:a8:e2:6a:da:85:85:0d:47:78:42:c8:03:20:
                        5f:08:08:03:45:4c:8b:5e:32:15:b3:44:ef:ab:65:
                        7c:ca:2d:66:6b:d0:e1:f6:45:6a:95:23:c6:11:e8:
                        b9:b9:76:3d:59:d5:6c:74:65:ae:e7:92:3f:f5:9a:
                        bf:3f:65:35:fc:d2:60:a1:a6:62:13:d9:75:18:c8:
                        02:94:ee:9e:f8:22:da:8f:f1:81:6f:e1:08:e1:be:
                        11:9f:0e:e1:ea:b5:15:f6:15:eb:e6:78:14:1f:40:
                        de:05:58:69:da:20:01:af:24:3a:db:c0:ac:e3:45:
                        2b:a5:5d:6c:69:42:f7:96:9d:2e:42:ef:c1:d5:85:
                        00:d1
                    Exponent: 65537 (0x10001)
            X509v3 extensions:
                X509v3 Key Usage: critical
                    Digital Signature, Certificate Sign, CRL Sign
                X509v3 Subject Key Identifier: 
                    93:6C:9A:74:D6:DF:01:B2:69:2C:07:D7:C1:3A:A9:56:B3:18:57:A4
                X509v3 Basic Constraints: critical
                    CA:TRUE, pathlen:1
                X509v3 Certificate Policies: 
                    Policy: 1.3.6.1.4.1.7879.13.26
                      CPS: http://corporate-pki.telekom.de/cps/cps.htm

        Signature Algorithm: sha1WithRSAEncryption
            04:bf:a1:e9:23:bf:6f:89:25:0f:bd:af:37:24:b5:e7:77:01:
            c7:e6:8d:7b:5c:05:7d:1e:1d:74:e2:33:93:26:1c:09:be:96:
            a5:0e:92:00:7e:a2:ee:75:59:e6:9e:60:99:b2:6a:63:92:95:
            1a:c4:26:41:19:ff:c2:69:b2:d2:ce:b6:e7:c4:31:5b:10:d7:
            5b:a9:3e:3c:35:5e:ea:20:19:45:b2:c0:cd:99:de:4d:52:80:
            d5:aa:a5:15:5e:a9:7a:b3:e8:6f:03:52:b1:51:96:46:49:d4:
            bc:89:07:86:cf:4e:23:85:72:72:cf:e4:c7:79:48:71:e7:29:
            d9:63:90:f5:b3:f9:aa:e5:d7:f1:5f:14:86:85:08:d8:ae:53:
            ff:34:71:f7:de:58:b9:a0:04:61:9d:ea:a4:cf:0e:8d:9e:d2:
            4c:cb:48:1a:f0:b9:3f:5f:88:7a:b7:5f:06:7a:e1:29:0e:a3:
            88:2c:6a:6d:3a:2e:dd:99:25:13:29:69:30:56:ac:bf:da:bf:
            4b:98:cb:e6:b6:71:bc:0c:06:0e:1b:8b:cd:b9:02:1c:78:99:
            3b:6c:2d:4b:8f:e5:fc:8f:ec:32:24:18:5d:61:b0:aa:ea:69:
            4a:44:68:7c:4f:4c:15:80:e3:6b:12:e0:92:86:e6:34:60:89:
            9c:31:13:13
    -----BEGIN CERTIFICATE-----
    MIID9TCCAt2gAwIBAgIBATANBgkqhkiG9w0BAQUFADBwMQswCQYDVQQGEwJERTEc
    MBoGA1UECgwTRGV1dHNjaGUgVGVsZWtvbSBBRzEVMBMGA1UECwwMVHJ1c3QgQ2Vu
    dGVyMSwwKgYDVQQDDCNEZXV0c2NoZSBUZWxla29tIEludGVybmFsIFJvb3QgQ0Eg
    MTAeFw0wNzExMTUxMjI4MzBaFw0yNzExMTUyMzU5NTlaMHAxCzAJBgNVBAYTAkRF
    MRwwGgYDVQQKDBNEZXV0c2NoZSBUZWxla29tIEFHMRUwEwYDVQQLDAxUcnVzdCBD
    ZW50ZXIxLDAqBgNVBAMMI0RldXRzY2hlIFRlbGVrb20gSW50ZXJuYWwgUm9vdCBD
    QSAxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq1WVBHm/llWUAn2c
    77D6KFSC7xZs4TvYz3iCSaDZQPVXfwXct/fBDoLOxXyWm5Js+jCKJm69vpq2AshV
    mv32NwIpHy3sGUwdPPM1KfPEVf5cIbciCHNlnsPeaEbAi0BpFVLRGHCm4uwIPase
    CD9J1C++p8W0Or6DyKjiatqFhQ1HeELIAyBfCAgDRUyLXjIVs0Tvq2V8yi1ma9Dh
    9kVqlSPGEei5uXY9WdVsdGWu55I/9Zq/P2U1/NJgoaZiE9l1GMgClO6e+CLaj/GB
    b+EI4b4Rnw7h6rUV9hXr5ngUH0DeBVhp2iABryQ628Cs40UrpV1saUL3lp0uQu/B
    1YUA0QIDAQABo4GZMIGWMA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQUk2yadNbf
    AbJpLAfXwTqpVrMYV6QwEgYDVR0TAQH/BAgwBgEB/wIBATBRBgNVHSAESjBIMEYG
    CSsGAQQBvUcNGjA5MDcGCCsGAQUFBwIBFitodHRwOi8vY29ycG9yYXRlLXBraS50
    ZWxla29tLmRlL2Nwcy9jcHMuaHRtMA0GCSqGSIb3DQEBBQUAA4IBAQAEv6HpI79v
    iSUPva83JLXndwHH5o17XAV9Hh104jOTJhwJvpalDpIAfqLudVnmnmCZsmpjkpUa
    xCZBGf/CabLSzrbnxDFbENdbqT48NV7qIBlFssDNmd5NUoDVqqUVXql6s+hvA1Kx
    UZZGSdS8iQeGz04jhXJyz+THeUhx5ynZY5D1s/mq5dfxXxSGhQjYrlP/NHH33li5
    oARhneqkzw6NntJMy0ga8Lk/X4h6t18GeuEpDqOILGptOi7dmSUTKWkwVqy/2r9L
    mMvmtnG8DAYOG4vNuQIceJk7bC1Lj+X8j+wyJBhdYbCq6mlKRGh8T0wVgONrEuCS
    huY0YImcMRMT
    -----END CERTIFICATE-----

    Certificate:
        Data:
            Version: 3 (0x2)
            Serial Number: 5161711930708270385 (0x47a215a72ec31d31)
            Signature Algorithm: sha256WithRSAEncryption
            Issuer: C=DE, O=Deutsche Telekom AG, OU=Trust Center, CN=Deutsche Telekom Internal Root CA 1
            Validity
                Not Before: Feb 11 14:21:38 2014 GMT
                Not After : Nov 15 23:59:59 2027 GMT
            Subject: C=DE, O=T-Systems International GmbH, OU=T-Systems Trust Center, ST=Nordrhein Westfalen/postalCode=57250, L=Netphen/street=Untere Industriestr. 20, CN=Internal Business CA 2
            Subject Public Key Info:
                Public Key Algorithm: rsaEncryption
                    RSA Public-Key: (2048 bit)
                    Modulus:
                        00:bb:8f:cb:46:5d:d6:45:34:d4:e6:e9:d9:b3:01:
                        62:84:8e:08:0c:9c:b5:f8:3f:b3:c6:ba:74:aa:92:
                        62:44:44:c8:45:7b:08:93:72:7c:7a:30:14:8c:aa:
                        9a:44:f1:07:51:7e:7a:65:e2:39:b1:35:af:c4:0d:
                        31:08:c0:fd:97:33:86:ed:b7:b1:a4:de:da:9a:db:
                        13:9a:b3:f0:45:89:5d:6e:67:e6:61:86:51:4b:c7:
                        c6:1e:7f:e5:db:ed:dd:1d:6b:8f:73:20:3f:2a:21:
                        e0:8e:18:4f:9d:f6:44:9d:ba:41:f7:3c:19:8a:46:
                        dc:bb:79:e0:cd:7d:93:6a:84:da:31:5f:4c:62:28:
                        21:f3:d6:2b:f3:f6:62:bb:ec:cd:2a:21:72:f0:63:
                        97:93:c4:52:d0:e4:83:43:54:59:d5:12:b8:cd:15:
                        c6:38:cc:00:d5:a1:b0:a9:3e:17:69:d1:dc:67:b6:
                        b1:d0:1a:58:0f:96:3f:d1:9e:43:2e:06:83:4e:c0:
                        f6:dd:ff:03:be:10:c8:60:b0:f0:09:e3:c0:04:f6:
                        38:e8:f9:0e:3b:c4:8d:c6:35:ce:60:6c:c7:1e:7d:
                        99:30:6c:1f:5c:de:2e:87:c7:13:bb:48:ba:5b:3c:
                        80:1a:77:e6:d9:74:ea:5d:46:e6:ff:eb:6a:25:64:
                        f8:37
                    Exponent: 65537 (0x10001)
            X509v3 extensions:
                X509v3 Key Usage: critical
                    Certificate Sign, CRL Sign
                X509v3 Subject Key Identifier: 
                    D4:80:25:C0:BE:96:46:AA:50:86:01:27:66:B9:74:E1:B2:E0:FA:3F
                X509v3 Authority Key Identifier: 
                    keyid:93:6C:9A:74:D6:DF:01:B2:69:2C:07:D7:C1:3A:A9:56:B3:18:57:A4

                X509v3 Basic Constraints: critical
                    CA:TRUE, pathlen:0
                X509v3 Certificate Policies: 
                    Policy: 1.3.6.1.4.1.7879.13.26
                      CPS: http://pki.telesec.de/cps/cps.html

                X509v3 CRL Distribution Points: 

                    Full Name:
                      URI:http://crl.sbca.telesec.de/rl/DT_Internal_Root_CA_1.crl

                    Full Name:
                      URI:ldap://ldap.sbca.telesec.de/CN=Deutsche%20Telekom%20Internal%20Root%20CA%201,OU=Trust%20Center,O=Deutsche%20Telekom%20AG,C=DE?AuthorityRevocationList

                Authority Information Access: 
                    OCSP - URI:http://ocsp.sbca.telesec.de/ocspr

        Signature Algorithm: sha256WithRSAEncryption
            7c:9f:c0:76:20:fd:67:60:0a:ad:b1:ce:35:51:08:fe:63:e3:
            8d:02:0c:01:4d:67:d3:33:f6:53:b1:fe:16:19:1e:1e:76:91:
            a1:74:93:2e:12:9e:b5:83:22:78:02:d7:57:fc:35:a2:03:a8:
            f8:9e:8e:61:6b:b9:41:0c:73:e7:97:45:76:1c:ba:26:49:06:
            6d:1e:35:88:81:11:72:21:da:8a:1b:26:cf:f7:87:49:e8:37:
            28:69:8e:b3:ec:1c:82:b6:1c:a0:77:09:6b:02:4c:27:91:69:
            6f:0e:c8:46:0f:2f:9b:6b:11:16:2e:84:64:b9:34:8d:f6:f7:
            36:c0:24:ce:52:d6:5b:e6:ee:58:38:42:20:50:44:b8:b8:72:
            48:89:51:ba:72:b1:4a:86:a4:e9:5e:a9:8c:23:c0:26:b5:ea:
            60:c6:fb:50:bd:44:8f:83:16:e0:29:ed:89:9f:5a:f9:5e:8a:
            08:32:86:38:96:7e:60:50:41:1f:b6:56:fc:3f:9b:58:71:74:
            15:f7:01:71:7e:f5:9d:9b:91:3c:87:f6:15:3a:63:9e:4a:ca:
            a6:77:b1:69:b7:e6:3e:9d:40:94:84:18:15:74:fd:e4:84:25:
            b4:37:e0:de:66:cf:c6:c1:82:0d:a8:84:52:3d:7f:f0:49:99:
            d9:af:72:02
    -----BEGIN CERTIFICATE-----
    MIIFrDCCBJSgAwIBAgIIR6IVpy7DHTEwDQYJKoZIhvcNAQELBQAwcDELMAkGA1UE
    BhMCREUxHDAaBgNVBAoME0RldXRzY2hlIFRlbGVrb20gQUcxFTATBgNVBAsMDFRy
    dXN0IENlbnRlcjEsMCoGA1UEAwwjRGV1dHNjaGUgVGVsZWtvbSBJbnRlcm5hbCBS
    b290IENBIDEwHhcNMTQwMjExMTQyMTM4WhcNMjcxMTE1MjM1OTU5WjCB2DELMAkG
    A1UEBhMCREUxJTAjBgNVBAoTHFQtU3lzdGVtcyBJbnRlcm5hdGlvbmFsIEdtYkgx
    HzAdBgNVBAsTFlQtU3lzdGVtcyBUcnVzdCBDZW50ZXIxHDAaBgNVBAgTE05vcmRy
    aGVpbiBXZXN0ZmFsZW4xDjAMBgNVBBETBTU3MjUwMRAwDgYDVQQHEwdOZXRwaGVu
    MSAwHgYDVQQJExdVbnRlcmUgSW5kdXN0cmllc3RyLiAyMDEfMB0GA1UEAxMWSW50
    ZXJuYWwgQnVzaW5lc3MgQ0EgMjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
    ggEBALuPy0Zd1kU01Obp2bMBYoSOCAyctfg/s8a6dKqSYkREyEV7CJNyfHowFIyq
    mkTxB1F+emXiObE1r8QNMQjA/Zczhu23saTe2prbE5qz8EWJXW5n5mGGUUvHxh5/
    5dvt3R1rj3MgPyoh4I4YT532RJ26Qfc8GYpG3Lt54M19k2qE2jFfTGIoIfPWK/P2
    YrvszSohcvBjl5PEUtDkg0NUWdUSuM0VxjjMANWhsKk+F2nR3Ge2sdAaWA+WP9Ge
    Qy4Gg07A9t3/A74QyGCw8AnjwAT2OOj5DjvEjcY1zmBsxx59mTBsH1zeLofHE7tI
    uls8gBp35tl06l1G5v/raiVk+DcCAwEAAaOCAd8wggHbMA4GA1UdDwEB/wQEAwIB
    BjAdBgNVHQ4EFgQU1IAlwL6WRqpQhgEnZrl04bLg+j8wHwYDVR0jBBgwFoAUk2ya
    dNbfAbJpLAfXwTqpVrMYV6QwEgYDVR0TAQH/BAgwBgEB/wIBADBIBgNVHSAEQTA/
    MD0GCSsGAQQBvUcNGjAwMC4GCCsGAQUFBwIBFiJodHRwOi8vcGtpLnRlbGVzZWMu
    ZGUvY3BzL2Nwcy5odG1sMIHrBgNVHR8EgeMwgeAwPaA7oDmGN2h0dHA6Ly9jcmwu
    c2JjYS50ZWxlc2VjLmRlL3JsL0RUX0ludGVybmFsX1Jvb3RfQ0FfMS5jcmwwgZ6g
    gZuggZiGgZVsZGFwOi8vbGRhcC5zYmNhLnRlbGVzZWMuZGUvQ049RGV1dHNjaGUl
    MjBUZWxla29tJTIwSW50ZXJuYWwlMjBSb290JTIwQ0ElMjAxLE9VPVRydXN0JTIw
    Q2VudGVyLE89RGV1dHNjaGUlMjBUZWxla29tJTIwQUcsQz1ERT9BdXRob3JpdHlS
    ZXZvY2F0aW9uTGlzdDA9BggrBgEFBQcBAQQxMC8wLQYIKwYBBQUHMAGGIWh0dHA6
    Ly9vY3NwLnNiY2EudGVsZXNlYy5kZS9vY3NwcjANBgkqhkiG9w0BAQsFAAOCAQEA
    fJ/AdiD9Z2AKrbHONVEI/mPjjQIMAU1n0zP2U7H+FhkeHnaRoXSTLhKetYMieALX
    V/w1ogOo+J6OYWu5QQxz55dFdhy6JkkGbR41iIERciHaihsmz/eHSeg3KGmOs+wc
    grYcoHcJawJMJ5Fpbw7IRg8vm2sRFi6EZLk0jfb3NsAkzlLWW+buWDhCIFBEuLhy
    SIlRunKxSoak6V6pjCPAJrXqYMb7UL1Ej4MW4CntiZ9a+V6KCDKGOJZ+YFBBH7ZW
    /D+bWHF0FfcBcX71nZuRPIf2FTpjnkrKpnexabfmPp1AlIQYFXT95IQltDfg3mbP
    xsGCDaiEUj1/8EmZ2a9yAg==
    -----END CERTIFICATE-----
{{- end -}}