apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-kong-conf
  labels: {{ include "kong.labels" $ | nindent 4 }}
data:
  nginx-kong.conf: |
  {{- if (eq (include "kong.isEnterpriseImage" $ ) "true") -}}
  {{- .Files.Get "conf/nginx-kong-ee.conf" | nindent 4 }}
  {{- else }}
  {{ .Files.Get "conf/nginx-kong.conf" | nindent 4 }}
  {{- end -}}