apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kong-admin-api
  labels: {{ include "kong.labels" $ | nindent 4 }}
data:
  configuration.sh: |
    {{- if hasKey .Values "configuration" }}
    {{- .Values.configuration | nindent 4 }}
    {{- else }}
    # 1
    # create service (upstream: http://localhost:8001)
    curl --request POST \
      --url http://localhost:8001/services \
      --header 'Content-Type: application/json' \
      --data '{
          "host": "localhost",
          "protocol": "http",
          "port": 8001,
          "name": "admin-api"
    }'

    # 2
    # create route (/admin-api) variable: hosts
    curl --request POST \
      --url http://localhost:8001/services/admin-api/routes \
      --header 'Content-Type: application/json' \
      --data '{
      "protocols": [
        "http",
        "https"
      ],
      "hosts": [
        "stargate-hyp-dev-zone-azure.dev.dhei.telekom.de"
      ],
      "name": "admin-api",
      "paths": [
        "/admin-api"
      ]
    }'

    # 3
    # create consumer (rover)
    curl --request POST \
      --url http://localhost:8001/consumers \
      --header 'Content-Type: application/json' \
      --data '{
          "username" : "rover",
          "custom_id": "rover"
        }'

    # 4
    # apply acl plugin to route (/admin-api) 
    # and allow group (rover)
    curl --request POST \
      --url http://localhost:8001/routes/admin-api/plugins \
      --header 'Content-Type: application/json' \
      --data '{
      "name": "acl",
      "config": {
      "allow":["rover"],
      "hide_groups_header": true
      }
    }'

    # 5
    # add consumer (rover) to group (rover)
    curl --request POST \
      --url http://localhost:8001/consumers/rover/acls \
      --header 'Content-Type: application/json' \
      --data '{
      "group": "rover"
    }'


    # 6
    # setup plugin (jwt-keycloak)
    # variable [allowed_iss]
    curl --request POST \
      --url http://localhost:8001/routes/admin-api/plugins \
      --header 'Content-Type: application/json' \
      --data '{
      "name": "jwt-keycloak",
      "config": {
      "allowed_iss" : ["https://iris-hyp-dev-zone-azure.dev.dhei.telekom.de/auth/realms/default"],
      "consumer_match" : true,
      "consumer_match_claim_custom_id" : true
      }
    }'
    {{- end -}}