apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-kong-template
  labels: {{ include "kong.labels" $ | nindent 4 }}
data:
  nginx_kong.lua: |
  {{- if (eq (include "kong.isEnterpriseImage" $ ) "true") -}}
  {{- .Files.Get "nginx/nginx_kong_ee.lua" | nindent 4 }}
  {{- else }}
  {{ .Files.Get "nginx/nginx_kong.lua" | nindent 4 }}
  {{- end -}}