apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector: 
    matchLabels: {{ include "kong.selector" $ | nindent 6 }}
  template:
    metadata:
      labels: {{ include "kong.labels" $ | nindent 8 }}
    spec:
      initContainers:
      - name: kong-init
        image: {{ include "kong.image" $ }}
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgresql
              key: password
        - name: KONG_PG_PORT
          value: '5432'
        - name: KONG_PG_HOST
          value: {{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
{{- if and .Values.enterprise.enabled .Values.enterprise.license }}
        - name: KONG_LICENSE_DATA
          value: {{ .Values.enterprise.license }}
{{- end }}
        command: [ "/bin/sh", "-c", "KONG_NGINX_DAEMON='off' kong migrations bootstrap" ]
      containers:
      - name: kong
        image: {{ include "kong.image" $ }}
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgresql
              key: password
        - name: KONG_PG_PORT
          value: '5432'
        - name: KONG_PG_HOST
          value: {{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
        - name: KONG_NGINX_WORKER_PROCESSES
          value: '1'
        - name: KONG_ADMIN_LISTEN
          value: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
        - name: KONG_PROXY_LISTEN
          value: '0.0.0.0:8000, 0.0.0.0:8443 ssl http2'
{{- if and .Values.enterprise.enabled .Values.enterprise.license }}
        - name: KONG_LICENSE_DATA
          value: {{ .Values.enterprise.license }}
{{- end }}
        command: [ "/bin/sh", "-c", "KONG_NGINX_DAEMON='off' kong start" ]
        ports:
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: admin-ssl
          containerPort: 8444
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu | default "750m" }}
            memory: {{ .Values.resources.requests.memory | default "1024Mi" }}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30