apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector: 
    matchLabels: {{ include "kong.selector" $ | nindent 6 }}
  template:
    metadata:
      labels: {{ include "kong.labels" $ | nindent 8 }}
    spec:
      initContainers:
      - name: kong-init
        image: {{ include "kong.image" $ }}
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgresql
              key: password
        - name: KONG_PG_PORT
          value: '{{ include "postgresql.port" $ }}'
        - name: KONG_PG_HOST
          value: {{ include "postgresql.host" $ }}
{{- if eq (include "kong.isEnterprise" $ ) "true" }}
        - name: KONG_LICENSE_DATA
          value: '{{ .Values.enterprise.license }}'
{{- end }}
        command: [ "/bin/sh", "-c", "KONG_NGINX_DAEMON='off' kong migrations bootstrap" ]
      containers:
      - name: kong
        image: {{ include "kong.image" $ }}
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgresql
              key: password
        - name: KONG_PG_PORT
          value: '{{ include "postgresql.port" $ }}'
        - name: KONG_PG_HOST
          value: {{ include "postgresql.host" $ }}
        - name: KONG_NGINX_WORKER_PROCESSES
          value: '1'
        - name: KONG_PROXY_LISTEN
          value: '0.0.0.0:8000, 0.0.0.0:8443 ssl http2'
        - name: KONG_ADMIN_LISTEN
          value: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
{{- if .Values.exposeAdminApi }}
        - name: KONG_ADMIN_API_URI
          value: 'https://{{ .Release.Name }}-admin-{{ .Release.Namespace }}.{{ .Values.global.domain.internal.url }}'
{{- end }}
{{- if and (eq .Values.manager.enabled true) (eq (include "kong.isEnterprise" $ ) "true") }}
        - name: KONG_ADMIN_GUI_LISTEN
          value: '0.0.0.0:8002, 0.0.0.0:8445 ssl'
        - name: KONG_ADMIN_GUI_URL
          value: 'https://{{ .Release.Name }}-manager-{{ .Release.Namespace }}.{{ .Values.global.domain.internal.url }}'
{{- if eq .Values.manager.disableAuth false }}
        - name: KONG_ENFORCE_RBAC
          value: 'on'
        - name: KONG_ADMIN_GUI_AUTH
          value: 'basic-auth'
        - name: KONG_ADMIN_GUI_SESSION_CONF
          value: '{"cookie_name":"kekse","secret":"monster"}'
{{- else }}
        - name: KONG_ENFORCE_RBAC
          value: 'off'
{{- end }}
{{- end }}
{{- if eq (include "kong.isEnterprise" $ ) "true" }}
        - name: KONG_LICENSE_DATA
          value: '{{ .Values.enterprise.license }}'
{{- end }}
        command: [ "/bin/sh", "-c", "KONG_NGINX_DAEMON='off' kong start" ]
        ports:
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: admin-ssl
          containerPort: 8444
          protocol: TCP
{{- if and (eq .Values.manager.enabled true) (eq (include "kong.isEnterprise" $ ) "true") }}
        - name: manager
          containerPort: 8002
          protocol: TCP
        - name: manager-ssl
          containerPort: 8445
          protocol: TCP
{{- end }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu | default "750m" }}
            memory: {{ .Values.resources.requests.memory | default "1024Mi" }}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30