apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  annotations: {{- include "kong.checksums" $ | nindent 4 }}
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector: 
    matchLabels: {{ include "kong.selector" $ | nindent 6 }}
  template:
    metadata:
      annotations: {{- include "kong.checksums" $ | nindent 8 }}
      labels: {{ include "kong.labels" $ | nindent 8 }}
    spec:
      {{- include "image_pull_secrets" $ | indent 6 }}
      initContainers:
      - name: kong-init
        image: {{ include "kong.image" $ }}
        imagePullPolicy: Always
        securityContext: {{ default .Values.securityContext | toYaml | nindent 10 }}
        env:
        - name: KONG_DATABASE
          value: postgres
{{- if eq .Values.rbac.enabled true }}
        - name: KONG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: kongAdminPassword
{{- end }}
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: postgresPassword
        - name: KONG_PG_PORT
          value: '{{ include "postgresql.port" $ }}'
        - name: KONG_PG_HOST
          value: '{{ include "postgresql.host" $ }}'
        - name: KONG_PG_USER
          value: '{{ include "postgresql.user" $ }}'
        - name: KONG_PG_DATABASE
          value: '{{ include "postgresql.database" $ }}'
{{- if eq .Values.postgres.externalDatabase.enabled true }}
{{- if .Values.postgres.externalDatabase.ssl }}
        - name: KONG_PG_SSL
          value: 'on'
{{- if .Values.postgres.externalDatabase.sslVerify }}
        - name: KONG_PG_SSL_VERIFY
          value: 'on'
        - name: KONG_LUA_SSL_TRUSTED_CERTIFICATE
          value: '/opt/kong/tls/init/lua-ssl-trusted-certificates.pem'
{{- end }}
{{- end }}
{{- end }}
{{- if eq (include "kong.isEnterprise" $ ) "true" }}
        - name: KONG_LICENSE_DATA
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: license
{{- end }}
        command: [ "/bin/sh", "-c", "KONG_NGINX_DAEMON='off' kong migrations bootstrap" ]
        volumeMounts:
          {{- include "kong.init.volumeMounts" $ | indent 8 }}
      containers:
{{- if eq .Values.jumper.enabled true }}
      - name: jumper
        image: {{ include "kong.jumper.image" $ }}
        imagePullPolicy: Always
        securityContext: {{ default .Values.jumper.securityContext | toYaml | nindent 10 }}
        resources: {{ .Values.jumper.resources | toYaml | nindent 10 }}
        ports:
        - containerPort: {{ .Values.jumper.port | default 8080 }} 
          name: jumper
          protocol: TCP
{{- end }}
      - name: kong
        image: {{ include "kong.image" $ }}
        imagePullPolicy: Always
        securityContext: {{ default .Values.securityContext | toYaml | nindent 10 }}
        env:
        {{- include "kong.nginx.directives" $ | indent 8 }}
        {{- include "kong.customPlugins.env" $ | indent 8 }}
        - name: KONG_PREFIX
          value: /kong
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: postgresPassword
        - name: KONG_PG_PORT
          value: '{{ include "postgresql.port" $ }}'
        - name: KONG_PG_HOST
          value: '{{ include "postgresql.host" $ }}'
        - name: KONG_PG_USER
          value: '{{ include "postgresql.user" $ }}'
        - name: KONG_PG_DATABASE
          value: '{{ include "postgresql.database" $ }}'
{{- if eq .Values.postgres.externalDatabase.enabled true }}
{{- if .Values.postgres.externalDatabase.ssl }}
        - name: KONG_PG_SSL
          value: 'on'
{{- if .Values.postgres.externalDatabase.sslVerify }}
        - name: KONG_PG_SSL_VERIFY
          value: 'on'
{{- end }}
{{- end }}
{{- end }}
        - name: KONG_NGINX_WORKER_PROCESSES
          value: '1'
        - name: KONG_PROXY_LISTEN
          value: '0.0.0.0:8000, 0.0.0.0:8443 ssl http2'
{{- if .Values.adminApi.enabled }}
        - name: KONG_ADMIN_LISTEN
{{- if .Values.adminApi.tls.enabled }}
          value: '0.0.0.0:8444 ssl'
{{- else }}
          value: '0.0.0.0:8001'
{{- end -}}
{{- if .Values.adminApi.ingress.enabled }}
        - name: KONG_ADMIN_API_URI
          value: '{{ include "kong.adminApi.url" . }}'
{{- end -}}
{{- end -}}
{{- if and (eq .Values.manager.enabled true) (eq (include "kong.isEnterprise" $ ) "true") }}
        - name: KONG_ADMIN_GUI_LISTEN
{{- if .Values.manager.tls.enabled }}
          value: '0.0.0.0:8445 ssl'
{{- else }}
          value: '0.0.0.0:8002'
{{- end }}
        - name: KONG_ADMIN_GUI_URL
          value: '{{ include "kong.manager.url" . }}'
{{- end -}}
{{- if and (eq .Values.portal.enabled true) (eq (include "kong.isEnterprise" $ ) "true") }}
        - name: KONG_PORTAL
          value: 'on'
{{- if .Values.portal.tls.enabled }}
        - name: KONG_PORTAL_GUI_LISTEN
          value: '0.0.0.0:8446 ssl'
        - name: KONG_PORTAL_API_LISTEN
          value: '0.0.0.0:8447 ssl'
{{- else }}
        - name: KONG_PORTAL_GUI_LISTEN
          value: '0.0.0.0:8003'
        - name: KONG_PORTAL_API_LISTEN
          value: '0.0.0.0:8004'
{{- end }}
        - name: KONG_PORTAL_GUI_HOST
          value: '{{ include "kong.portal.host" . }}'
        - name: KONG_PORTAL_GUI_PROTOCOL
          value: {{ include "kong.portal.protocol" . }}
{{- if eq .Values.rbac.enabled true }}
        - name: KONG_PORTAL_AUTH
          value: 'basic-auth'
        - name: KONG_PORTAL_SESSION_CONF
          value: '{"secret":"{{ .Values.portal.session.secret }}"}'
{{- end -}}
{{- end -}}
{{- if eq .Values.rbac.enabled true }}
        - name: KONG_ENFORCE_RBAC
          value: 'on'
        - name: KONG_ADMIN_GUI_AUTH
          value: 'basic-auth'
        - name: KONG_ADMIN_GUI_SESSION_CONF
          value: '{"secret":"{{ .Values.manager.session.secret }}"}'
{{- end -}}
{{- if eq (include "kong.isEnterprise" $ ) "true" }}
        - name: KONG_LICENSE_DATA
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: license
{{- end }}
{{- if or .Values.zipkin.luaSslTrustedCertificate .Values.postgres.externalDatabase.sslVerify }}
        - name: KONG_LUA_SSL_TRUSTED_CERTIFICATE
          value: '/opt/kong/tls/lua-ssl-trusted-certificates.pem'
{{- end }}
        command: [ "/bin/sh", "-c", "KONG_NGINX_DAEMON='off' kong start" ]
        resources: {{ .Values.resources | toYaml | nindent 10 }}
        ports:
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
{{- if .Values.prometheus.enabled }}
        - name: metrics
          containerPort: {{ .Values.prometheus.port | default 9542 }}
          protocol: TCP
{{- end -}}
{{- if .Values.adminApi.enabled -}}
{{- if .Values.adminApi.tls.enabled }}
        - name: admin-ssl
          containerPort: 8444
          protocol: TCP
{{- else }}
        - name: admin
          containerPort: 8001
          protocol: TCP
{{- end -}}
{{- end }}
{{- if and (eq .Values.manager.enabled true) (eq (include "kong.isEnterprise" $ ) "true") -}}
{{- if .Values.manager.tls.enabled }}
        - name: manager-ssl
          containerPort: 8445
          protocol: TCP
{{- else }}
        - name: manager
          containerPort: 8002
          protocol: TCP
{{- end -}}
{{- end -}}
{{- if and (eq .Values.portal.enabled true) (eq (include "kong.isEnterprise" $ ) "true") -}}
{{- if .Values.portal.tls.enabled }}
        - name: portal-ssl
          containerPort: 8446
          protocol: TCP
        - name: portal-api-ssl
          containerPort: 8447
          protocol: TCP
{{- else }}
        - name: portal
          containerPort: 8003
          protocol: TCP
        - name: portal-api
          containerPort: 8004
          protocol: TCP
{{- end -}}
{{- end }}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        {{- include "kong.volumeMounts" $ | indent 8 }}
        {{- include "kong.customPlugins.volumeMounts" $ | indent 8 }}
      volumes:
      {{- include "kong.init.volumes" $ | indent 6 }}
      {{- include "kong.volumes" $ | indent 6 }}
      {{- include "kong.customPlugins.volumes" $ | indent 6 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
