{{- if not .Values.postgres.externalDatabase.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgresql
  labels: {{ include "postgresql.labels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.configuration.replicas | default 1 }}
  selector:
    matchLabels: {{ include "postgresql.selector" $ | nindent 6 }}
  template:
    metadata:
      labels: {{ include "postgresql.labels" $ | nindent 8 }}
    spec:
      {{- include "image_pull_secrets" $ | indent 6 }}
      containers:
      - name: {{ .Release.Name }}-postgresql
        image: {{ include "postgres.image" $ }}
        imagePullPolicy: Always
        securityContext: {{ .Values.postgres.configuration.securityContext | toYaml | nindent 10 }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user | default "kong" }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: postgresPassword
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database | default "kong" }}
        # for centos and rhel we do have different environment variables
        - name: POSTGRESQL_USER
          value: {{ .Values.postgres.user | default "kong" }}
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: postgresPassword
        - name: POSTGRESQL_DATABASE
          value: {{ .Values.postgres.database | default "kong" }}
        livenessProbe:
          tcpSocket:
            port:  {{ include "postgresql.port" $ }}
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: {{ include "postgresql.port" $ }}
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - 'pg_isready -U kong'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
{{- toYaml .Values.postgres.configuration.resources | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /tmp
          name: {{ .Release.Name }}-postgresql-tmp
        - mountPath: {{ .Values.postgres.configuration.data_locations | default "/var/lib/pgsql/data" }}
          name: {{ .Release.Name }}-postgresql-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: {{ .Release.Name }}-postgresql-tmp
        emptyDir: {}
      - name: {{ .Release.Name }}-postgresql-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-database-pvc
{{- end -}}
