apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  annotations:
  {{- include "kong.annotations" $ | nindent 4 }}
  {{- include "kong.checksums" $ | nindent 4 }}
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector: 
    matchLabels: {{ include "kong.selector" $ | nindent 6 }}
  template:
    metadata:
      annotations: 
      {{- include "kong.annotations" $ | nindent 8 }}
      {{- include "kong.checksums" $ | indent 8 }}
{{- if eq .Values.prometheus.enabled true }}
        prometheus.io/path: '{{ .Values.prometheus.path | default "/metrics" }}'
        prometheus.io/scrape: 'true'
        prometheus.io/port: '{{ .Values.prometheus.port | default 9542 }}'
{{- end }}
      labels: {{ include "kong.labels" $ | nindent 8 }}{{ include "status-monitor.labels" $ | nindent 8 }}
    spec:
      {{- include "image_pull_secrets" $ | indent 6 }}
      initContainers:
      - name: kong-install-plugins
        image: {{ include "kongplugins.image" $ }}
        imagePullPolicy: Always
        securityContext: {{ default .Values.plugins.initContainer.securityContext | toYaml | nindent 10 }}
        command:
        - /bin/sh
        - -c
        - |-
          {{- range .Values.plugins.enabled }}
          {{ printf "luarocks install --local ~/plugins/kong-plugin-%s*" . }}
          {{- end }}
        volumeMounts:
          {{- include "kongplugins.volumeMounts" $ | indent 8 }}
      containers:
{{- if eq .Values.jumper.enabled true }}
      - name: jumper
        image: {{ include "kong.jumper.image" $ }}
        imagePullPolicy: Always
        securityContext: {{ default .Values.jumper.securityContext | toYaml | nindent 10 }}
        resources: {{ .Values.jumper.resources | toYaml | nindent 10 }}
        ports:
        - containerPort: {{ .Values.jumper.port | default 8080 }} 
          name: jumper
          protocol: TCP
        volumeMounts:
          {{- include "kong.jumper.volumeMounts" $ | indent 8 }}
        env:
        {{- include "kong.jumper.env" $ | indent 8 }}
{{- end }}
      - name: kong
        image: {{ include "kong.image" $ }}
        imagePullPolicy: Always
        securityContext: {{ default .Values.securityContext | toYaml | nindent 10 }}
        env:
        {{- include "kong.nginx.directives" $ | indent 8 }}
        {{- include "kong.customPlugins.env" $ | indent 8 }}
        {{- include "kong.env" $ | indent 8 }}
        command: [ "/bin/sh", "-c", "KONG_NGINX_DAEMON='off' kong start" ]
        resources: {{ .Values.resources | toYaml | nindent 10 }}
        ports:
{{- if .Values.proxy.tls.enabled }}
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
{{- else }}
        - name: proxy
          containerPort: 8000
          protocol: TCP
{{- end -}}
{{- if .Values.prometheus.enabled }}
        - name: metrics
          containerPort: {{ .Values.prometheus.port | default 9542 }}
          protocol: TCP
{{- end -}}
{{- if .Values.adminApi.enabled -}}
{{- if .Values.adminApi.tls.enabled }}
        - name: admin-ssl
          containerPort: 8444
          protocol: TCP
{{- else }}
        - name: admin
          containerPort: 8001
          protocol: TCP
{{- end -}}
{{- end }}
{{- if and (eq .Values.manager.enabled true) (eq (include "kong.isEnterprise" $ ) "true") -}}
{{- if .Values.manager.tls.enabled }}
        - name: manager-ssl
          containerPort: 8445
          protocol: TCP
{{- else }}
        - name: manager
          containerPort: 8002
          protocol: TCP
{{- end -}}
{{- end -}}
{{- if and (eq .Values.portal.enabled true) (eq (include "kong.isEnterprise" $ ) "true") -}}
{{- if .Values.portal.tls.enabled }}
        - name: portal-ssl
          containerPort: 8446
          protocol: TCP
        - name: portal-api-ssl
          containerPort: 8447
          protocol: TCP
{{- else }}
        - name: portal
          containerPort: 8003
          protocol: TCP
        - name: portal-api
          containerPort: 8004
          protocol: TCP
{{- end -}}
{{- end }}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        {{- include "kong.volumeMounts" $ | indent 8 }}
      volumes:
      {{- include "kongplugins.volumes" $ | indent 6 }}
      {{- include "kong.volumes" $ | indent 6 }}
      {{- include "kong.jumper.volumes" $ | indent 6 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
