{{- if eq .Values.global.platform "kubernetes" }}
{{- if .Values.exposeAdminApi }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-admin
  labels: {{ include "kong.labels" $ | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: {{ .Release.Name }}-admin-{{ .Release.Namespace }}.{{ .Values.global.domain }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.global.externalDnsTarget }}
    kubernetes.io/ingress.class: external-nginx
spec:
  rules:
  - host: {{ .Release.Name }}-admin-{{ .Release.Namespace }}.{{ .Values.global.domain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-admin
            servicePort: kong-admin
{{- end }}
{{- end }}