apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-circuitbreaker
  labels: {{ include "kong.labels" $ | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: triton-ingress
    kubernetes.io/tls-acme: "true" 
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true" 
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"


spec:
  rules:
  - host: stargate-io-develop-circuitbreaker.dev.dhei.telekom.de
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-circuitbreaker
            servicePort: circuitbreaker
