{{- if and (eq .Values.portal.enabled true) .Values.enterprise.license }}
{{- if eq .Values.global.platform "kubernetes" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-portal
  labels: {{ include "kong.labels" $ | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: {{ .Release.Name }}-portal-{{ .Release.Namespace }}.{{ .Values.global.domain.internal.url }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.global.externalDnsTarget }}
    kubernetes.io/ingress.class: external-nginx
spec:
  rules:
  - host: {{ .Release.Name }}-portal-{{ .Release.Namespace }}.{{ .Values.global.domain.internal.url }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-portal
            servicePort: kong-portal
{{- end }}
{{- end }}