{{- if and (eq .Values.manager.enabled true) .Values.enterprise.license }}
{{- if eq .Values.global.platform "kubernetes" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-manager
  labels: {{ include "kong.labels" $ | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: {{ .Release.Name }}-manager-{{ .Release.Namespace }}.{{ .Values.global.domain.internal.url }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-manager
            servicePort: kong-manager
{{- end }}
{{- end }}