{{- if and (eq .Values.manager.enabled true) (eq (include "kong.isEnterprise" $ ) "true") -}}
{{- if eq .Values.global.platform "kubernetes" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-manager
  labels: {{ include "kong.labels" $ | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/hostname: {{ .Release.Name }}-manager-{{ .Release.Namespace }}.{{ .Values.global.domain }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.global.externalDnsTarget }}
    kubernetes.io/ingress.class: external-nginx
spec:
  rules:
  - host: {{ .Release.Name }}-manager-{{ .Release.Namespace }}.{{ .Values.global.domain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-manager
            servicePort: kong-manager
{{- end -}}
{{- end -}}