{{- if eq .Values.global.platform "kubernetes" }}
{{- if and .Values.portal.ingress.enabled .Values.portal.enabled (eq (include "kong.isEnterprise" $ ) "true") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-portal
  labels: {{ include "kong.labels" $ | nindent 4 }}
{{- include "kong.merged.portal.annotations" $ | nindent 2 }}
spec:
  rules:
  - host: {{ include "kong.portal.host" . }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-portal
              port:
{{- if .Values.portal.tls.enabled }}
                name: portal-ssl
{{- else }}
                name: portal
{{- end }}
  tls:
  - hosts:
    - {{ include "kong.portal.host" . }}
{{- include "kong.portal.ingress.tlsSecret" . | nindent 4 -}}
{{- end -}}
{{- end -}}
