{{- if eq .Values.global.platform "kubernetes" }}
{{- if .Values.proxy.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-proxy
  labels: {{ include "kong.labels" $ | nindent 4 }}
{{- include "kong.merged.proxy.annotations" $ | nindent 2 }}
spec:
  rules:
  - host: {{ include "kong.proxy.host" . }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-proxy
            servicePort: proxy-ssl
{{- end -}}
{{- end -}}