{{- if eq .Values.global.platform "kubernetes" -}}
{{- if eq (include "kong.adminApi.ingress.enabled" $) "true" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-admin
  labels: {{ include "kong.labels" $ | nindent 4 }}
{{- include "kong.merged.adminApi.annotations" $ | nindent 2 }}
spec:
  rules:
  - host: {{ include "kong.adminApi.host" . }}
    http:
      paths:
        - path: {{ include "kong.adminApi.ingress.path" . }}
          backend:
            serviceName: {{ .Release.Name }}-proxy
{{- if .Values.proxy.tls.enabled }}
            servicePort: proxy-ssl
{{- else }}
            servicePort: proxy
{{- end }}
  tls:
  - hosts:
    - {{ include "kong.adminApi.host" . }}
{{- end -}}
{{- end -}}
