{{- if eq .Values.global.platform "kubernetes" -}}
{{- if eq (include "kong.adminApi.ingress.enabled" $) "true" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-admin
  labels: {{ include "kong.labels" $ | nindent 4 }}
{{- include "kong.merged.adminApi.annotations" $ | nindent 2 }}
spec:
  rules:
  - host: {{ include "kong.adminApi.host" . }}
    http:
      paths:
        - path: {{ include "kong.adminApi.ingress.path" . }}
          backend:
{{- if (eq (include "kong.isEnterprise" $ ) "true") }}
            serviceName: {{ .Release.Name }}-admin
{{- if .Values.adminApi.tls.enabled }}
            servicePort: admin-ssl
{{- else }}
            servicePort: admin
{{- end }}
{{- else }}
            serviceName: {{ .Release.Name }}-proxy
{{- if .Values.proxy.tls.enabled }}
            servicePort: proxy-ssl
{{- else }}
            servicePort: proxy
{{- end }}
{{- end }}
  tls:
  - hosts:
    - {{ include "kong.adminApi.host" . }}
{{- end -}}
{{- end -}}