{{- if and .Values.adminApi.enabled .Values.adminApi.ingress.enabled }}
{{- $svcPort := .Values.adminApi.tls.enabled | ternary "proxy-ssl" "proxy" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-admin
  labels:
    {{- include "kong.labels" $ | nindent 4 }}
{{- include "kong.merged.adminApi.annotations" $ | nindent 2 }}
spec:
  {{- if .Values.adminApi.ingress.className }}
  ingressClassName: {{ .Values.adminApi.ingress.className }}
  {{- end }}
  {{- if .Values.adminApi.ingress.tls }}
  tls:
    {{- range .Values.adminApi.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.adminApi.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-proxy
                port:
                  name: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
