{{- if .Values.exposeAdminApi }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-admin
  labels: {{ include "kong.labels" $ | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: {{ .Release.Name }}-admin-{{ .Release.Namespace }}.{{ .Values.global.domain.internal.url }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-proxy
            servicePort: kong-admin
{{- end }}