{{- if eq .Values.global.platform "kubernetes" }}
{{- if and .Values.manager.ingress.enabled .Values.manager.enabled true (eq (include "kong.isEnterprise" $ ) "true") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-manager
  labels: {{ include "kong.labels" $ | nindent 4 }}
{{- include "kong.merged.manager.annotations" $ | nindent 2 }}
spec:
  rules:
  - host: {{ include "kong.manager.host" . }}
    http:
      paths:
        - path: /
          backend:
            service:
              name: {{ .Release.Name }}-manager
              port:
{{- if .Values.manager.tls.enabled }}
                name: manager-ssl
{{- else }}
                name: manager
{{- end }}
  tls:
  - hosts:
    - {{ include "kong.manager.host" . }}
{{- end -}}
{{- end -}}
