{{- if and (include "kong.isMigrationsJob" $) (.Values.adminApi.enabled) (eq (include "kong.isZipkinEnabled" $) "true") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-plugin-migration-zipkin
  labels: {{ include "kong.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/weight": "-10"
spec:
  backoffLimit: {{ .Values.prometheus.setupJob.backoffLimit | default 15 }}
  activeDeadlineSeconds: {{ .Values.prometheus.setupJob.activeDeadlineSeconds | default 3600 }}
  template:
    spec:
      {{- include "image_pull_secrets" $ | indent 6 }}
      containers:
      - name: zipkin-deletion
        image: {{ include "job.image" $ }}
        securityContext: {{ default .Values.jobs.securityContext | toYaml | nindent 10 }}
        env:
        - name: X_TARDIS_GATEWAY_ADMIN_BASE64
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: gatewayAdminBase64
        {{- if eq .Values.rbac.enabled true }}
        - name: KONG_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: kongAdminPassword
        {{- end }}
        command:        
          - /bin/bash
          - -c
          - |-
            echo "Removing old Kong ENI flavoured Zipkin plugin via DELETE {{ include "kong.adminApi.serviceUrl" . }}/plugins"

            ADMIN_API_HTTP_RETURN_CODE=`curl -Is -o /dev/null -w "%{http_code}" -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" {{ if eq .Values.rbac.enabled true -}}-H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD"{{- end }} -X GET {{ include "kong.adminApi.serviceUrl" . }}`
            if [ "$ADMIN_API_HTTP_RETURN_CODE" != "200" ]; then
                echo "Kong Admin-API unreachable"
                exit 1
            fi

            CONFIG_CALL_HTTP_RETURN_CODE=`curl \
            -o /dev/null \
            -w "%{http_code}" \
            -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" \
            {{- if eq .Values.rbac.enabled true }}
            -H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD" \
            {{- end }}
            -X DELETE {{ include "kong.adminApi.serviceUrl" . }}/plugins/{{ .Values.zipkin.setupJob.pluginId }}`

            if [ "$CONFIG_CALL_HTTP_RETURN_CODE" != "204" ]; then
              echo "Plugin deletion failed"
              exit 1
            fi
      restartPolicy: OnFailure
{{- end -}}
