{{- if and .Values.zipkin.enabled ( not ( eq .Values.zipkin.collectorUrl "" )) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-zipkin-setup
  labels: {{ include "kong.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: {{ .Values.zipkin.setupJob.backoffLimit | default 15 }}
  activeDeadlineSeconds: {{ .Values.zipkin.setupJob.activeDeadlineSeconds | default 3600 }}
  template:
    spec:
      {{- include "image_pull_secrets" $ | indent 6 }}
      containers:
      - name: tif-base-image
        image: mtr.external.otc.telekomcloud.com/tif-public/tif-base-image:1.0.0
        securityContext: {{ default .Values.jobs.securityContext | toYaml | nindent 10 }}
        env:
        {{- if eq .Values.rbac.enabled true }}
        - name: KONG_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: kongAdminPassword
         {{- end }}
        command:        
          - /bin/bash
          - -c
          - |- 
            echo "Enabling Kong plugin via POST {{ include "kong.adminApi.serviceUrl" . }}/plugins"

            HTTP_RETURN_CODE=`curl -Is -o /dev/null -w "%{http_code}" {{ if eq .Values.rbac.enabled true -}}-H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD"{{- end }} -X GET {{ include "kong.adminApi.serviceUrl" . }}`
            if [ "$HTTP_RETURN_CODE" == "200" ]; then
              curl \
              {{- if eq .Values.rbac.enabled true }}
              -H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD" \
              {{- end }}
              -X PUT {{ include "kong.adminApi.serviceUrl" . }}/plugins/{{ .Values.zipkin.setupJob.pluginId }} \
              --data "name=zipkin" \
              --data "config.http_endpoint={{ .Values.zipkin.collectorUrl }}" \
              --data "config.sample_ratio={{ .Values.zipkin.sampleRatio | default 0.001 }}" \
              --data "config.include_credential={{ .Values.zipkin.includeCredential | default "true" }}" \
              --data "config.default_service_name={{ .Values.zipkin.defaultServiceName | default .Release.Name }}"
            else
                echo "Kong Admin-API unreachable"
                exit 1
            fi
      restartPolicy: OnFailure
{{- end }}
