{{- if eq .Values.prometheus.enabled true }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-prometheus-setup
  labels: {{ include "kong.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.prometheus.setupJob.backoffLimit | default 15 }}
  activeDeadlineSeconds: {{ .Values.prometheus.setupJob.activeDeadlineSeconds | default 3600 }}
  template:
    spec:
      {{- include "image_pull_secrets" $ | indent 6 }}
      containers:
      - name: {{ .Release.Name }}-prometheus-setup
        image: mtr.external.otc.telekomcloud.com/tif-public/tif-base-image:1.0.0
        securityContext: {{ default .Values.jobs.securityContext | toYaml | nindent 10 }}
        env:
        {{- if eq .Values.rbac.enabled true }}
        - name: KONG_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: kongAdminPassword
        {{- end }}
        command:        
          - /bin/bash
          - -c
          - |-
            echo "Enabling Kong plugin via POST {{ include "kong.adminApi.serviceUrl" . }}/plugins"

            HTTP_RETURN_CODE=`curl -Is -o /dev/null -w "%{http_code}" {{ if eq .Values.rbac.enabled true -}}-H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD"{{- end }} -X GET {{ include "kong.adminApi.serviceUrl" . }}`
            if [ "$HTTP_RETURN_CODE" == "200" ]; then
              curl \
            {{- if eq .Values.rbac.enabled true }}
              -H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD" \
            {{- end }}
              -X PUT {{ include "kong.adminApi.serviceUrl" . }}/plugins/{{ .Values.prometheus.setupJob.pluginId }} \
              --data "name=prometheus" 
            else
                echo "Kong Admin-API unreachable"
                exit 1
            fi
      restartPolicy: OnFailure
{{- end -}}
