{{- if not .Values.postgres.externalDatabase.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-database-pvc
  labels: {{ include "postgresql.labels" $ | nindent 4 }}
{{- if .Values.postgres.persistence }}
  {{- if .Values.postgres.persistence.keepOnDelete }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end -}}
{{- end }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.global.storageclass | default "cns" }}
  resources: {{ .Values.postgres.persistence.resources | toYaml | nindent 4 }}
{{- end -}}