{{- if not .Values.postgres.externalDatabase -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-database-pvc
  labels: {{ include "postgresql.labels" $ | nindent 4 }}
{{- if .Values.postgres.configuration.pvc }}
  {{- if .Values.postgres.configuration.pvc.keepOnDelete }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end -}}
{{- end }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.global.storageclass | default "cns" }}
{{- end -}}