{{- if eq .Values.global.platform "openshift" }}
{{- if .Values.proxy.ingress.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-proxy
  labels: {{ include "kong.labels" $ | nindent 4 }}
{{- include "kong.merged.proxy.annotations" $ | nindent 2 }}
spec:
  host: {{ include "kong.proxy.host" . }}
  port:
    targetPort: proxy-ssl
  to:
    kind: Service
    name: {{ .Release.Name }}-proxy
    weight: 100
  tls:
    termination: passthrough
status:
  ingress:
    - host: ""
{{- end -}}
{{- end -}}
