{{- if eq .Values.global.platform "openshift" }}
{{- if and .Values.manager.ingress.enabled .Values.manager.enabled true -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-manager
  labels: {{ include "kong.labels" $ | nindent 4 }}
{{- include "kong.merged.manager.annotations" $ | nindent 2 }}
spec:
  host: {{ include "kong.manager.host" . }}
  port:
{{- if .Values.manager.tls.enabled }}
    targetPort: manager-ssl
{{- else }}
    targetPort: manager
{{- end }}
  to:
    kind: Service
    name: {{ .Release.Name }}-manager
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
status:
  ingress:
    - host: ""
{{- end -}}
{{- end -}}