{{- if and (eq .Values.manager.enabled true) (eq (include "kong.isEnterprise" $ ) "true") -}}
{{- if eq .Values.global.platform "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-manager
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  host: {{ .Release.Name }}-manager-{{ .Release.Namespace }}.{{ .Values.global.domain }}
  port:
    targetPort: kong-manager
  to:
    kind: Service
    name: {{ .Release.Name }}-manager
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
status:
  ingress:
    - host: ""
{{- end -}}
{{- end -}}