{{- if and (eq .Values.portal.enabled true) .Values.enterprise.license }}
{{- if eq .Values.global.platform "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-portal-api
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  host: {{ .Release.Name }}-portal-api-{{ .Release.Namespace }}.{{ .Values.global.domain.internal.url }}
  port:
    targetPort: kong-portal-api
  to:
    kind: Service
    name: {{ .Release.Name }}-portal-api
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
status:
  ingress:
    - host: ""
{{- end }}
{{- end }}