{{- if and (eq .Values.manager.enabled true) .Values.enterprise.license }}
{{- if eq .Values.global.platform "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-manager
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  host: {{ .Release.Name }}-manager-{{ .Release.Namespace }}.{{ .Values.global.domain.internal.url }}
  port:
    targetPort: kong-manager-ssl
  to:
    kind: Service
    name: {{ .Release.Name }}-manager
    weight: 100
  tls:
    termination: passthrough
status:
  ingress:
    - host: ""
{{- end }}
{{- end }}