apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-proxy
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  host: kong-proxy-{{ .Values.global.domain.internal.url }}
  port:
    targetPort: kong-proxy
  to:
    kind: Service
    name: {{ .Release.Name }}-proxy
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge