{{- if eq .Values.global.platform "openshift" -}}
{{- if and .Values.adminApi.enabled .Values.adminApi.ingress.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-admin
  labels: {{ include "kong.labels" $ | nindent 4 }}
{{- include "kong.merged.adminApi.annotations" $ | nindent 2 }}
spec:
  host: {{ include "kong.adminApi.host" . }}
  port:
{{- if .Values.adminApi.tls.enabled }}
    targetPort: admin-ssl
{{- else }}
    targetPort: admin
{{- end }}
  to:
    kind: Service
    name: {{ .Release.Name }}-admin
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
status:
  ingress:
    - host: ""
{{- end -}}
{{- end -}}
