apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-trusted-ca-certificates
  labels: {{- include "kong.labels" $ | nindent 4 }}
type: Opaque
data:
{{- if eq .Values.sslVerify true }}
  trusted-ca-certificates.pem: {{ (.Values.trustedCaCertificates | default "# Set trustedCaCertificates in values.yaml") | b64enc }}
{{- end }}
{{- if or .Values.zipkin.luaSslTrustedCertificate .Values.postgres.externalDatabase.sslVerify }}
  lua-ssl-trusted-certificates.pem: {{ (include "kong.luaSslTrustedCertificates" $  | default "# Set luaSslTrustedCertificate in values.yaml") | b64enc }}
{{- end }}
{{- end -}}