{{- if eq .Values.sslVerify true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-trusted-ca-certificates
  labels: {{- include "kong.labels" $ | nindent 4 }}
type: Opaque
data:
  trusted-ca-certificates.pem: {{ (.Values.trustedCaCertificates | default "# Set trustedCaCertificates in values.yaml") | b64enc }}
{{- end -}}