apiVersion: v1
kind: Secret
metadata:
  {{- $name := printf "%s-%s" .Release.Name "htpasswd" }}
  name: {{ $name }}
  labels: {{- include "kong.labels" $ | nindent 4 }}
type: Opaque
data:
{{- $failOnUnsetValues := eq (toString .Values.global.failOnUnsetValues) "true" }}
{{- $defaultUnsetValue := "changeme" }}
{{- $unsetValues := list }}
{{- $htpasswd := .Values.adminApi.htpasswd }}
{{- if not (and (eq $htpasswd $defaultUnsetValue) $failOnUnsetValues) }}
  .htpasswd: {{ $htpasswd | b64enc | quote }}
{{- else }}
{{- $unsetValues = append $unsetValues "htpasswd" }}
{{- end }}
{{- if and .Values.global.failOnUnsetValues (gt (len $unsetValues) 0) }}
{{- fail (printf "Values not set in %s: %v" $name $unsetValues) }}
{{- end }}