{{- if or (eq .Values.sslVerify true) .Values.zipkin.luaSslTrustedCertificate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-trusted-ca-certificates
  labels: {{- include "kong.labels" $ | nindent 4 }}
type: Opaque
data:
{{- if eq .Values.sslVerify true }}
  trusted-ca-certificates.pem: {{ (.Values.trustedCaCertificates | default "# Set trustedCaCertificates in values.yaml") | b64enc }}
{{- end }}
{{- if .Values.zipkin.luaSslTrustedCertificate }}
  lua-ssl-trusted-certificates.pem: {{ (.Values.zipkin.luaSslTrustedCertificate | default "# Set luaSslTrustedCertificate in values.yaml" ) | b64enc }}
{{- end }}
{{- end -}}