apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-htpasswd
  labels: {{- include "kong.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- $gatewayAdminApiKey := dict "password" .Values.adminApi.gatewayAdminApiKey "rules" .Values.global.passwordRules }}
  .htpasswd: {{ (htpasswd "admin" ($gatewayAdminApiKey | include "passutil.validated")) | b64enc }}