apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  selector: {{ include "postgresql.selector" $ | nindent 4 }}
type: Opaque
data:
  password: {{ (.Values.postgres.password | default (randAlphaNum 10)) | b64enc }}