apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nginx-kong-conf
  labels: {{- include "kong.labels" $ | nindent 4 }}
type: Opaque
data:
  nginx-kong.conf: {{ tpl (.Files.Get "conf/nginx-kong.conf") . | b64enc }}    