apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kong-rbac
  labels: {{ include "kong-rbac.labels" $ | nindent 4 }}
type: Opaque
data:
  kongPassword: {{ (.Values.manager.rbac_password | default "kong") | b64enc }}
