{{- if .Values.issuerService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  {{- $name := printf "%s-%s" (include "kong.fullname" .) "issuer-service" }}
  name: {{ $name }}
  labels: {{ include "kong.labels" $ | nindent 4 }}
type: Opaque
data:
{{- $failOnUnsetValues := eq (toString .Values.global.failOnUnsetValues) "true" }}
{{- $defaultUnsetValue := "changeme" }}
{{- $unsetValues := list }}
{{- $jsonWebKey := .Values.issuerService.jsonWebKey }}
{{- if not (and (eq $jsonWebKey $defaultUnsetValue) $failOnUnsetValues) }}
  jsonWebKey: {{ $jsonWebKey | b64enc | quote }}
{{- else }}
{{- $unsetValues = append $unsetValues "jsonWebKey" }}
{{- end }}
{{- $publicKey := .Values.issuerService.publicKey }}
{{- if not (and (eq $publicKey $defaultUnsetValue) $failOnUnsetValues) }}
  publicKey: {{ $publicKey | b64enc | quote }}
{{- else }}
{{- $unsetValues = append $unsetValues "publicKey" }}
{{- end }}
{{- if and .Values.global.failOnUnsetValues (gt (len $unsetValues) 0) }}
{{- fail (printf "Values not set in %s: %v" $name $unsetValues) }}
{{- end }}
{{- end -}}
