apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-migrations
  labels: {{ include "kong.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
type: Opaque
data:
  license: {{ .Values.enterprise.license | b64enc | quote }}
{{- if .Values.rbac.enabled }}
  {{- $kongAdminPassword := dict "password" .Values.rbac.kongAdminPassword "rules" .Values.global.passwordRules }}
  kongAdminPassword: {{ $kongAdminPassword | include "passutil.validated" | b64enc | quote }}
{{- end }}
  {{- $postgresPassword := dict "password" .Values.postgres.password "rules" .Values.global.passwordRules }}
  postgresPassword: {{ $postgresPassword | include "passutil.validated" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "kong.labels" $ | nindent 4 }}
type: Opaque
data:
  license: {{ .Values.enterprise.license | b64enc | quote }}
{{- if .Values.rbac.enabled }}
  {{- $kongAdminPassword := dict "password" .Values.rbac.kongAdminPassword "rules" .Values.global.passwordRules }}
  kongAdminPassword: {{ $kongAdminPassword | include "passutil.validated" | b64enc | quote }}
{{- end }}
  {{- $postgresPassword := dict "password" .Values.postgres.password "rules" .Values.global.passwordRules }}
  postgresPassword: {{ $postgresPassword | include "passutil.validated" | b64enc | quote }}