apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-issuer-service
  labels: {{ include "kong.labels" $ | nindent 4 }}
type: Opaque
data:
  jsonWebKey: {{ .Values.issuerService.jsonWebKey | b64enc | quote }}
  publicKey: {{ .Values.issuerService.publicKey | b64enc | quote }}
