apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "kong.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- $gatewayAdminApiKey := dict "password" .Values.adminApi.gatewayAdminApiKey "rules" .Values.global.passwordRules }}
  gatewayAdminBase64: {{ printf "admin:%s" ($gatewayAdminApiKey | include "passutil.validated") | b64enc | b64enc | quote}}
  {{- $postgresPassword := dict "password" .Values.database.password "rules" .Values.global.passwordRules }}
  postgresPassword: {{ $postgresPassword | include "passutil.validated" | b64enc | quote }}