{{- if and (eq .Values.portal.enabled true) (eq (include "kong.isEnterprise" $ ) "true") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-portal-api
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  selector: {{ include "kong.selector" $ | nindent 4 }}
  ports:
  - name: kong-portal-api
    port: 8004
    targetPort: 8004
    protocol: TCP
  - name: kong-portal-api-ssl
    port: 8447
    targetPort: 8447
    protocol: TCP
{{- end -}}