{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  annotations: {{- include "kong.annotations.prometheus" $ | nindent 4 }}
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  selector: {{ include "kong.selector" $ | nindent 4 }}
  ports:
  - name: kong-metrics
    port: {{ .Values.prometheus.port | default 9542 }}
    targetPort: {{ .Values.prometheus.port | default 9542 }}
    protocol: TCP
{{- end -}}