{{- if and (eq .Values.manager.enabled true) (eq (include "kong.isEnterprise" $ ) "true") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-manager
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  selector: {{ include "kong.selector" $ | nindent 4 }}
  ports:
  - name: kong-manager
    port: 8002
    targetPort: 8002
    protocol: TCP
  - name: kong-manager-ssl
    port: 8445
    targetPort: 8445
    protocol: TCP
{{- end -}}