apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-circuitbreaker
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  selector: {{ include "kong.selector" $ | nindent 4 }}
  ports:
  - name: circuitbreaker
    port: 8084
    targetPort: 8084
