apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  selector: {{ include "kong.selector" $ | nindent 4 }}
  ports:
  - name: kong-admin
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: kong-admin-ssl
    port: 8444
    targetPort: 8444
    protocol: TCP