{{- if and (.Values.plugins.prometheus.enabled) (.Values.plugins.prometheus.serviceMonitor.enabled) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  labels: {{ include "kong.labels" $ | nindent 4 }}
  {{- include "common.status-monitor.labels" $ | nindent 4 }}
  {{- include "status-monitor.labels" $ | nindent 4 }}
spec:
  selector: {{ include "kong.selector" $ | nindent 4 }}
  ports:
  - name: metrics
    port: 9542
    targetPort: metrics
    protocol: TCP
  - name: jumper-metrics
    port: 9544
    targetPort: jumper
    protocol: TCP
{{- end -}}
